#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

# Architecture
ifneq ($(TARGET_SUPPORTS_64_BIT_APPS),true)

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
ifeq ($(TARGET_CPU_VARIANT_RUNTIME_ENABLE),true)
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a53
else # !TARGET_CPU_VARIANT_RUNTIME_ENABLE
TARGET_CPU_VARIANT := cortex-a53
endif # TARGET_CPU_VARIANT_RUNTIME_ENABLE

else # TARGET_SUPPORTS_64_BIT_APPS

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
ifeq ($(TARGET_CPU_VARIANT_RUNTIME_ENABLE),true)
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a53
else # !TARGET_CPU_VARIANT_RUNTIME_ENABLE
TARGET_CPU_VARIANT := cortex-a53
endif # TARGET_CPU_VARIANT_RUNTIME_ENABLE

ifneq ($(TARGET_SUPPORTS_32_BIT_APPS),false)
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
ifeq ($(TARGET_CPU_VARIANT_RUNTIME_ENABLE),true)
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a53
else # !TARGET_CPU_VARIANT_RUNTIME_ENABLE
TARGET_2ND_CPU_VARIANT := cortex-a53
endif # TARGET_CPU_VARIANT_RUNTIME_ENABLE
endif # !TARGET_SUPPORTS_32_BIT_APPS

endif # TARGET_SUPPORTS_64_BIT_APPS

# Bootloader (lk2nd)
ifneq ($(filter msm8916% msm8929 msm8936 msm8939%,$(TARGET_QCOM_SOC)),)
    TARGET_LK2ND_PLATFORM := msm8916
else ifneq ($(filter msm8917 msm8920 msm8937 msm8940 qcm2150 qm215 sdm429 sdm439,$(TARGET_QCOM_SOC)),)
    TARGET_LK2ND_PLATFORM := msm8952
endif
TARGET_LK2ND_PLATFORM ?= msm8953

# Boot parameters
MAINLINE_QCOM_SOC_ANDROIDBOOT_PARAMS := \
    androidboot.boot_devices=soc@0/7824900.mmc

# Kernel
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_IMAGE_NAME := Image.gz
BOARD_KERNEL_PAGESIZE := 2048
ifneq ($(filter msm8916% msm8929 msm8936 msm8939%,$(TARGET_QCOM_SOC)),)
    BOARD_KERNEL_TAGS_OFFSET := 0x01E00000
    BOARD_RAMDISK_OFFSET := 0x02000000
endif
BOARD_KERNEL_TAGS_OFFSET ?= 0x00000100
BOARD_RAMDISK_OFFSET ?= 0x01000000
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)


# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)

# Properties
TARGET_VENDOR_PROP += \
    $(MAINLINE_QCOM_COMMON_SOC_PATH)/properties/vendor.prop
